version: "3"
name: "backend-dev"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        - RUNNING_USER=${RUNNING_USER:-0:0}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-patient-data}
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/${MONGO_INITDB_DATABASE:-patient-data}}
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-patient-data}

volumes:
  mongo-data:
