FROM node:18-alpine AS build

ARG RUNNING_USER

RUN mkdir /.npm && chown $RUNNING_USER /.npm && \
  mkdir /node_modules && chown $RUNNING_USER /node_modules
RUN apk add --update --no-cache python3 python3-dev build-base 

USER $RUNNING_USER

WORKDIR /app

CMD id && npm ci && npx nodemon app.js
